# Allgemeine Informationen

Auf dieser Seite findet ihr alle wichtigen Informationen zur Erstellung von Online-Veranstaltungen am Institut für Erziehungswissenschaft.

* [Rechenzentrum: Digitale Lehrszenarien zur Überbrückung der Einschränkungen in der Lehre wegen Corona](https://ilias.uni-freiburg.de/goto.php?target=crs_1492956&client_id=unifreiburg)
* [Rechenzentrum Freiburg: Digitale Lehre im SoSe 20 - Informieren und loslegen!](https://ilias.uni-freiburg.de/goto.php?target=cat_1488395)

## Software und Hardware am Institut

* [Camtasia 6 Zugänge für Dozierende (Videoschnitt)](https://www.techsmith.de/camtasia.html)
* [Articulate Storyline](https://articulate.com/): Erstellung von Web-Based Trainings. Eine Lizenz im Multimedia-PC vorhanden (Kabuff)
* [Captivate](https://www.adobe.com/de/products/captivate.html)
* [Kahoot](https://kahoot.it/): Mit Kahoot kann man Live-Umfragen in der Lehre erstellen. Wir haben 7 Lizenzen für diese Software.
* [MaxQda](https://www.maxqda.de/): Tool zur Auswertung von Texten. 5 USB-Sticks mit aktivierten Lizenzen
* [Limesurvey](https://umfrage.ezw.uni-freiburg.de/index.php/admin/authentication/sa/login): Erstellung von Online-Umfragen für die Forschung.

## Hardware am Institut

* [2 USB Mikrophone zur Aufnahme von Powerpoints](https://www.amazon.de/Rode-Studioqualit%C3%A4t-USB-Kondensatormikrofon-Tischstativ-Popschutz/dp/B00KQPGRRE): Befinden sich im Institut. Ein Mikro befindet sich im Kabuff, das andere im Stahlschrank (Nachfrage bei Christian)
* Diverse Beamer für die Lehre
* Multimedia PC (im Kabuff)

