# Online-Meetings mit Zoom

Zoom [(zoom.us)](https://zoom.us) ist ein Service für Meetings und Webinare.
Hier finden Sie eine Übersicht an Videoanleitungen rund um Zoom.

## Meetings erstellen

<iframe
  width="560"
  height="315"
  src="https://www.youtube-nocookie.com/embed/QAwXDo0DiWg"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>

## Meetings aufzeichnen

<iframe
  width="560"
  height="315"
  src="https://www.youtube-nocookie.com/embed/kGxR5_BHgEY"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>

Wählen Sie "Aufzeichnen" und "Auf diesem Computer aufzeichnen".

Nach dem Beenden des Meetings wird eine mp4-Datei erstellt, die Sie [auf Ilias hochladen](videos.html#videos-auf-ilias-hochladen) können.

## Audio- und Videoeinstellungen

<iframe
  width="560"
  height="315"
  src="https://www.youtube-nocookie.com/embed/_mK57mE4AcE?start=134"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>

## Bedienelemente zur Moderation

<iframe
  width="560"
  height="315"
  src="https://www.youtube-nocookie.com/embed/Hv1c6OCm_tU"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>

## Tipps zur Moderation

<iframe
  width="560"
  height="315"
  src="https://www.youtube-nocookie.com/embed/d0SUJZiJYA0?start=188"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
></iframe>

## Offizielle Dokumentation

Im offiziellen [Zoom Help Center](https://support.zoom.us/hc/de/categories/201146643) finden Sie eine vollständige Dokumentation von Zoom.

Hier eine Übersicht der Themen:

**Teilnehmen und starten**

* <a href="https://support.zoom.us/hc/de/articles/201362613-Wie-hoste-ich-ein-Videomeeting-" class="article-list-link">Wie hoste ich ein Videomeeting?</a>

* <a href="https://support.zoom.us/hc/de/articles/201362193-Wie-nehme-ich-an-einem-Meeting-teil-" class="article-list-link">Wie nehme ich an einem Meeting teil?</a>

* <a href="https://support.zoom.us/hc/de/articles/201362423-Wie-starte-ich-ein-geplantes-Meeting-als-Host-und-wie-nehme-ich-daran-teil-" class="article-list-link">Wie starte ich ein geplantes Meeting als Host und wie nehme ich daran teil?</a>

* <a href="https://support.zoom.us/hc/de/articles/201362183-Wie-lade-ich-andere-zur-Teilnahme-am-Meeting-ein-" class="article-list-link">Wie lade ich andere zur Teilnahme am Meeting ein?</a>

* <a href="https://support.zoom.us/hc/de/articles/206122046-Kann-ich-simultane-Meetings-moderieren-" class="article-list-link">Kann ich simultane Meetings moderieren?</a>

* <a href="https://support.zoom.us/hc/de/articles/115002262083-Wie-f%C3%BChre-ich-vor-dem-Beitritt-zu-einem-Meeting-einen-Test-durch-" class="article-list-link">Wie führe ich vor dem Beitritt zu einem Meeting einen Test durch?</a>

**Planen**

* <a href="https://support.zoom.us/hc/de/articles/201362413-Wie-plane-ich-Meetings-" class="article-list-link">Wie plane ich Meetings?</a>

* <a href="https://support.zoom.us/hc/de/articles/214973206-Planung-von-wiederkehrenden-Meetings" class="article-list-link">Planung von wiederkehrenden Meetings</a>

* <a href="https://support.zoom.us/hc/de/articles/202828525-Beitritt-vor-Host" class="article-list-link">Beitritt vor Host</a>

* <a href="https://support.zoom.us/hc/de/articles/203276937-Pers%C3%B6nliche-Meeting-ID-PMI-verwenden" class="article-list-link">Persönliche Meeting-ID (PMI) verwenden</a>

* <a href="https://support.zoom.us/hc/de/articles/201362533-Jetzt-treffen-vs-Geplante-Meetings" class="article-list-link">Jetzt treffen vs Geplante Meetings</a>

* <a href="https://support.zoom.us/hc/de/articles/360000488243-Kalenderintegration-in-Desktop-Client" class="article-list-link">Kalenderintegration in Desktop Client</a>

**Videowebinar**

* <a href="https://support.zoom.us/hc/de/articles/200917029-Erste-Schritte-mit-dem-Webinar" class="article-list-link">Erste Schritte mit dem Webinar</a>

* <a href="https://support.zoom.us/hc/de/articles/115004834466-Teilnehmer-im-Webinar-verwalten" class="article-list-link">Teilnehmer im Webinar verwalten</a>

* <a href="https://support.zoom.us/hc/de/articles/204619915-Ein-Webinar-mit-Registrierung-planen" class="article-list-link">Ein Webinar mit Registrierung planen</a>

* <a href="https://support.zoom.us/hc/de/articles/206316975-Webinar-%C3%9Cbungssitzung" class="article-list-link">Webinar-Übungssitzung</a>

* <a href="https://support.zoom.us/hc/de/articles/360000489183-On-Demand-Webinare" class="article-list-link">On-Demand-Webinare</a>

* <a href="https://support.zoom.us/hc/de/articles/216354763-Planung-eines-wiederkehrenden-Meetings" class="article-list-link">Planung eines wiederkehrenden Meetings</a>

**Einstellungen und Bedienelemente**

* <a href="https://support.zoom.us/hc/de/articles/201362623-Informationen-zu-den-Einstellungen" class="article-list-link">Informationen zu den Einstellungen</a>

* <a href="https://support.zoom.us/hc/de/articles/200941109-Bedienelemente-f%C3%BCr-Teilnehmer-in-einem-Meeting" class="article-list-link">Bedienelemente für Teilnehmer in einem Meeting</a>

* <a href="https://support.zoom.us/hc/de/articles/201362603-Bedienelemente-des-Hosts-in-einem-Meeting" class="article-list-link">Bedienelemente des Hosts in einem Meeting</a>

* <a href="https://support.zoom.us/hc/de/articles/206476313-Videogruppenr%C3%A4ume-verwalten" class="article-list-link">Videogruppenräume verwalten</a>

* <a href="https://support.zoom.us/hc/de/articles/203650445-Chat-im-Meeting" class="article-list-link">Chat im Meeting</a>

* <a href="https://support.zoom.us/hc/de/articles/115004809306-Steuerung-und-Deaktivieren-vom-Chat-im-Meeting" class="article-list-link">Steuerung und Deaktivieren vom Chat im Meeting</a>

**Häufig gestellte Fragen**


* <a href="https://support.zoom.us/hc/de/articles/201362843-Pers%C3%B6nliche-Meeting-ID-PMI-und-Pers%C3%B6nlicher-Link-" class="article-list-link">Persönliche Meeting-ID (PMI) und Persönlicher Link </a>

* <a href="https://support.zoom.us/hc/de/articles/201362773-Wo-kann-ich-den-Text-der-Meeting-Einladung-finden-" class="article-list-link">Wo kann ich den Text der Meeting-Einladung finden?</a>

* <a href="https://support.zoom.us/hc/de/articles/201362713-E-Mail-Benachrichtigung-Ihre-Meeting-Teilnehmer-warten-" class="article-list-link">E-Mail-Benachrichtigung ‚‚Ihre Meeting-Teilnehmer warten!‘‘</a>

* <a href="https://support.zoom.us/hc/de/articles/201362373-Was-ist-die-Meeting-ID-" class="article-list-link">Was ist die Meeting-ID?</a>

* <a href="https://support.zoom.us/hc/de/articles/202460676-Ist-mein-Meeting-zeitlich-begrenzt-" class="article-list-link">Ist mein Meeting zeitlich begrenzt?</a>

* <a href="https://support.zoom.us/hc/de/articles/201362523-Warum-tritt-bei-meinem-Meeting-eine-Zeit%C3%BCberschreitung-ein-" class="article-list-link">Warum tritt bei meinem Meeting eine Zeitüberschreitung ein?</a>